app:
    user-agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36
    chat-id: 
    telegram-token:
    mangas:
      - title: Fire Force
        url: https://manganelo.com/manga/xqfw3591566265037
        chapter: 203
      - title: Jagaaaaaan
        url: https://manganelo.com/manga/eupo237211575286777
        chapter: 83
      - title: The God of High School
        url: https://manganelo.com/manga/read_the_god_of_high_school_manga
        chapter: 447
      - title: UQ Holder!
        url: https://manganelo.com/manga/read_uq_holder_manga_online_for_free
        chapter: 168
      - title: Neverland
        url: https://manganelo.com/manga/yakusoku_no_neverland
        chapter: 163
      - title: Record of Ragnarok
        url: https://manganelo.com/manga/vy918232
        chapter: 25
      - title: Radiant
        url: https://manganelo.com/manga/radiant
        chapter: 92
      - title: Onepunch-Man (ONE)
        url: https://manganelo.com/manga/read_onepunchman_one
        chapter: 118
      - title: Onepunch-Man
        url: https://manganelo.com/manga/read_one_punch_man_manga_online_free3
        chapter: 125
      - title: One Piece
        url: https://manganelo.com/manga/read_one_piece_manga_online_free4
        chapter: 967
      - title: New Prince of Tennis
        url: https://manganelo.com/manga/new_prince_of_tennis
        chapter: 250
      - title: Nanatsu No Taizai
        url: https://manganelo.com/manga/read_nanatsu_no_taizai_manga_online_free
        chapter: 338
      - title: My Hero Academia
        url: https://manganelo.com/manga/read_boku_no_hero_academia_manga
        chapter: 254
      - title: Demon Slayer
        url: https://manganelo.com/manga/kimetsu_no_yaiba
        chapter: 189
      - title: Kengan Omega
        url: https://manganelo.com/manga/cd918233
        chapter: 46
      - title: Jigokuraku
        url: https://manganelo.com/manga/jigokuraku_kaku_yuuji
        chapter: 82
      - title: Heart Gear
        url: https://manganelo.com/manga/no919133
        chapter: 19
      - title: Hajime No Ippo
        url: https://manganelo.com/manga/read_hajime_no_ippo_manga
        chapter: 1285
      - title: Black Clover
        url: https://manganelo.com/manga/black_clover
        chapter: 235
      - title: Boruto
        url: https://manganelo.com/manga/boruto_naruto_next_generations
        chapter: 41
      - title: Chainsaw Man
        url: https://manganelo.com/manga/ix917953
        chapter: 53
      - title: Dai Dark
        url: https://manganelo.com/manga/sg919827
        chapter: 8
      - title: Dr Stone
        url: https://manganelo.com/manga/dr_stone
        chapter: 134
      - title: Dragon Ball Super
        url: https://manganelo.com/manga/dragon_ball_super
        chapter: 55
      - title: Fairy Tail 100 Years Quest
        url: https://manganelo.com/manga/uv917720
        chapter: 47
      - title: Tomb Raider King
        url: https://manganelo.com/manga/eg919734
        chapter: 35
      - title: Solo Leveling
        url: https://manganelo.com/manga/pn918005
        chapter: 102
